import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";



const inter = localFont({ src: "../../public/font/MontserratAlternates.ttf", preload:true});

export const metadata: Metadata = {
  title: "Чернецов Никита | Веб-разработчик",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
